puts "The students of Villains Academy"
"------------"
puts "Lord Voldemort"
puts "Doctor Robotnik"
puts "Freddy Vorhees"
puts "M Bison"
puts "Kefka"
puts "Terminator"
puts "The Riddler"
puts "Patrik Bateman"
puts "Robert Killgrave"
puts "Uchiha Sasuke"
puts "Yagami Light"
